/* extras.js — 补充词典与规则
 * 摘自「GitHub 中文化插件」(maboloshi/github-chinese, GPL-3.0)
 * + 本插件自备补充词条。由 content.js 合并进 I18N 词库（locals.js 优先，其次本文件，最后 dictionary.js）。
 */
'use strict';
window.__GH_EXTRAS__ = {

  /* =========================== 补充静态词典 =========================== */
  static: {
    /* -------- 通用输入框 / 侧边栏 -------- */
    'Find a repository...': '查找仓库…',
    'Find a repository…': '查找仓库…',
    'Ask anything or type @ to add context': '请输入问题，或输入 @ 添加上下文',
    'Type / to search': '按 / 搜索',

    /* -------- Dashboard 快捷操作 / Copilot 建议 -------- */
    'Debug': '调试',
    'Agent': '智能体',
    'Auto': '自动',

    /* -------- Copilot 桌面应用推广横幅 -------- */
    'The GitHub Copilot app': 'GitHub Copilot 应用',
    'An agent-driven desktop experience built natively on GitHub.': '原生构建于 GitHub 之上的智能体桌面应用。',
    'Download for Windows': '下载 Windows 版',

    /* -------- Issues 页面（/issues/assigned） -------- */
    'Mentioning me': '提到我',
    'No saved views': '无保存视图',
    'Try a different search query.': '尝试其他搜索查询。',
    'Learn more about searching and filtering issues and pull requests.': '详细了解搜索和过滤议题与拉取请求。',
    'Set as default view': '设为默认视图',
    'Default to this view when visiting /issues': '访问 /issues 时默认使用此视图',

    /* -------- 仓库列表页（/repos） -------- */
    'Admin access': '管理员访问',
    'Collapse sidebar': '收起侧边栏',
    'ProTip!': '专业提示！',
    "Don't forget that you can create saved views to keep track of your most important repositories!": '别忘了你可以创建已保存视图，以跟踪最重要的仓库！',
    'Other': '其他',

    /* -------- Copilot 设置页（/settings/copilot/features） -------- */
    'Inline suggestions': '行内建议',
    'Included credits': '包含额度',
    'Upgrade your Copilot plan for higher usage limits, premium models, AI reviews and more.': '升级您的 Copilot 方案以获取更高使用限额、高级模型、AI 审阅等。',
    'Upgrade plan': '升级方案',
    'Coming soon': '即将推出',
    'Enables access to Copilot in the cloud, including GitHub.com and GitHub Mobile. This policy replaces previous Copilot Chat and Copilot cloud agent policies.': '支持在云端访问 Copilot，包括 GitHub.com 和 GitHub Mobile。此策略将替代之前的 Copilot Chat 和 Copilot 云端智能体策略。',
    'Semantic indexing for Non-GitHub Repositories': '非 GitHub 仓库的语义索引',
    'If enabled you can use Semantic indexing for Non-GitHub Repositories to index your non-GitHub repositories in VSCode.': '如果启用，您可以使用 Semantic indexing for Non-GitHub Repositories 功能在 VSCode 中为您的非 GitHub 仓库建立索引。',
    'Copilot CLI': 'Copilot 命令行',
    'You can use the GitHub Copilot app. Enforcement begins 7/27th, 2026 in version 1.1 of the GitHub Copilot app. The Copilot CLI policy continues to govern the GitHub Copilot App until version 1.1': '您可以使用 GitHub Copilot 应用。该策略将于 2026 年 7 月 27 日在 GitHub Copilot 应用 1.1 版中开始强制执行。在 1.1 版之前，GitHub Copilot 应用仍受 Copilot CLI 策略约束。',

    /* -------- 项目页（/projects） -------- */
    'recently viewed': '最近浏览',

    /* -------- 代码空间（/codespaces、/codespaces/templates） -------- */
    'Codespaces': '代码空间',
    'Blank': '空白',
    'Start with a blank canvas or import any packages you need.': '从空白画布开始，或导入您需要的任何包。',
    'A popular JavaScript library for building user interfaces based on UI components.': '一个用于构建基于 UI 组件的用户界面的流行 JavaScript 库。',
    'JupyterLab is the latest web-based interactive development environment for notebooks, code, and data.': 'JupyterLab 是最新的基于 Web 的交互式笔记本、代码和数据开发环境。',
    'A full-stack web application template written in C#.': '一个使用 C# 编写的全栈 Web 应用模板。',
    'A full-stack web framework for building dynamic websites that deliver a rich user experience.': '一个用于构建提供丰富用户体验的动态网站的全栈 Web 框架。',
    'Express is a minimal and flexible Node.js web application framework.': 'Express 是一个极简且灵活的 Node.js Web 应用框架。',
    'Next.js is a React framework that gives you building blocks to create web applications.': 'Next.js 是一个 React 框架，为您提供构建 Web 应用的模块。',
    'Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.': 'Django 是一个高级 Python Web 框架，鼓励快速开发和简洁、实用的设计。',
    'Flask is a lightweight web application framework.': 'Flask 是一个轻量级 Web 应用框架。',
    'A fast 3kB alternative to React with the same modern API.': '一个体积仅 3kB、拥有与 React 相同现代 API 的快速替代方案。',
    'Examples running via semihosting output on an Arm FVP simulation model.': '通过 Arm FVP 仿真模型上的 semihosting 输出运行的示例。',

    /* -------- Copilot 智能体页（/copilot/agents） -------- */
    'Copilot cloud agent handles routine tasks so you can focus on core work': 'Copilot 云端智能体处理日常任务，让您专注于核心工作',
    'Save time by offloading testing, dependency upgrades, migrations and maintenance to agents. Create pull requests from Copilot Chat, CLI, IDEs or assign an issue to Copilot to get started.': '将测试、依赖升级、迁移和维护工作交给智能体，节省时间。从 Copilot Chat、CLI、IDE 创建拉取请求，或分配一个议题给 Copilot 即可开始。',
    'Copilot cloud agent capabilities': 'Copilot 云端智能体功能',
    'View Copilot cloud agent capabilities': '查看 Copilot 云端智能体功能',
    'Access to Copilot cloud agent has been disabled by your administrator.': 'Copilot 云端智能体访问已被您的管理员禁用。',

    /* ================= Copilot / AI 聊天界面 ================= */
    // 优化目标下拉（Optimized for: ...）
    'Optimized for: Balance': '优化目标：均衡',
    'Optimized for: Efficiency': '优化目标：效率',
    'Optimized for: Intelligence': '优化目标：智能',
    'Optimized for': '优化目标',
    'Efficiency': '效率',
    'Prioritizes speed and efficiency': '优先速度与效率',
    'Balance': '均衡',
    'Balances speed and intelligence': '平衡速度与智能',
    'Intelligence': '智能',
    'Prioritizes intelligence': '优先智能',
    // 输入框与发送
    'Ask': '询问',
    'Ask Copilot': '询问 Copilot',
    'Message Copilot': '给 Copilot 发消息',
    'Type a message': '输入消息',
    'Send': '发送',
    'Send message': '发送消息',
    'Send prompt': '发送提示',
    'Add context': '添加上下文',
    'Add more context': '添加更多上下文',
    'Mention a file, folder, or symbol': '提及文件、文件夹或符号',
    'Select a repository': '选择仓库',
    'Search for a repository': '搜索仓库',
    'Recent repositories': '最近的仓库',
    // 对话管理
    'New chat': '新对话',
    'New conversation': '新对话',
    'Open full chat': '打开完整聊天',
    'Close chat': '关闭聊天',
    'Chat history': '聊天历史',
    'History': '历史记录',
    'No chats yet': '暂无对话',
    'Start a chat': '开始对话',
    'View all chats': '查看所有对话',
    'Rename chat': '重命名对话',
    'Delete chat': '删除对话',
    // 生成过程
    'Working': '处理中',
    'Working…': '处理中…',
    'Thinking': '思考中',
    'Thinking…': '思考中…',
    'Copilot is working…': 'Copilot 正在处理…',
    'Copilot is working on your request…': 'Copilot 正在处理你的请求…',
    'Stop': '停止',
    'Stop responding': '停止响应',
    'Stop generation': '停止生成',
    'Regenerate': '重新生成',
    'Continue': '继续',
    // 回答反馈与操作
    'Good response': '回答不错',
    'Bad response': '回答有误',
    'Rate this response': '为这个回答评分',
    'Thanks for your feedback': '感谢你的反馈',
    'Show code': '显示代码',
    'Hide code': '隐藏代码',
    'Insert in file': '插入文件',
    'Apply in editor': '在编辑器中应用',
    'Copy': '复制',
    'Copied': '已复制',
    'Explain': '解释',
    'Docstring': '文档字符串',
    'Tests': '测试',
    'Fix issues': '修复问题',
    'Create issue': '创建议题',
    'Blockquote': '引用块',
    // 模式切换
    'Edit': '编辑',
    'Plan': '计划',
    'Debug': '调试',
    'Agent': '智能体',
    'Auto': '自动',
    // 免责声明 / 提示语
    'Copilot may make mistakes. Consider checking responses.': 'Copilot 可能会犯错，请注意核查回复。',
    'Copilot can make mistakes. Consider checking responses.': 'Copilot 可能会犯错，请注意核查回复。',
    'AI generated. Review carefully.': 'AI 生成，请仔细审查。',
    // 编码智能体
    'Assign issue to Copilot': '将议题分配给 Copilot',
    'Copilot will start working on it': 'Copilot 将开始处理',
    'Start working': '开始工作',
    'New Copilot session': '新 Copilot 会话',
    'Resume': '恢复',
    'Session started': '会话已开始',
    'Working on it': '正在处理',
    'Open session': '打开会话',
    'Pull request created': '拉取请求已创建',

    /* -------- Copilot 面板建议问题 / 提示语 -------- */
    'Ask about the github url:': '询问关于 GitHub URL 的信息：',
    'Ask about the GitHub URL:': '询问关于 GitHub URL 的信息：',
    'What questions can I ask?': '我可以询问哪些问题？',
    'What is the best way to get started with Copilot?': '开始使用 Copilot 的最佳方式是什么？',
    "What's new in Copilot?": 'Copilot 有什么新功能？',
    'What can Copilot do?': 'Copilot 能做什么？',

    /* -------- Copilot 面板窗口按钮（aria-label） -------- */
    'Full screen': '全屏',
    'Enter full screen': '进入全屏',
    'Exit full screen': '退出全屏',
    'Minimize': '最小化',
    'Start a new chat': '开始新对话',
    'Open history': '打开历史记录',
    'Recent chats': '最近对话',
    'Hide sidebar': '隐藏侧边栏',
    'Show sidebar': '显示侧边栏',

    /* ================= 企业版页面（/account/entiseprises/new 等） ================= */
    '30-day free trial': '30 天免费试用',
    "Unlock GitHub's premium features": "解锁 GitHub 的高级功能",
    'What you get in your premium free trial:': '高级版免费试用包含：',
    // 试用要点（整行与拆分两种 DOM 结构都覆盖）
    'Enterprise: Seamlessly plan, build, and ship great software with an extensible DevOps platform': '企业版：通过可扩展的 DevOps 平台无缝规划、构建并交付出色的软件',
    'Seamlessly plan, build, and ship great software with an extensible DevOps platform': '通过可扩展的 DevOps 平台无缝规划、构建并交付出色的软件',
    'Enterprise:': '企业版：',
    'Advanced Security: Spend less time fixing security vulnerabilities with AI-powered AppSec tools': '高级安全：借助 AI 驱动的 AppSec 工具，减少修复安全漏洞的时间',
    'Spend less time fixing security vulnerabilities with AI-powered AppSec tools': '借助 AI 驱动的 AppSec 工具，减少修复安全漏洞的时间',
    'Advanced Security:': '高级安全：',
    // 选择企业类型
    'Start by choosing an enterprise type': '首先选择企业类型',
    'Your enterprise type determines whether members can contribute to public repositories and if they can use their personal GitHub accounts.': '你的企业类型决定了成员是否可以向公共仓库贡献，以及他们是否可以使用个人 GitHub 帐户。',
    'Learn more about enterprise types': '详细了解企业类型',
    'Learn more about enterprise types.': '详细了解企业类型。',
    // 个人帐户型企业
    'Recommended for public and private work': '推荐用于公共和私有工作',
    'Enterprise with personal accounts': '使用个人帐户的企业',
    'For public, open source and private work, that allows members to access your repositories with their personal GitHub accounts.': '适用于公共、开源和私有工作，允许成员使用个人 GitHub 帐户访问你的仓库。',
    'Get started with personal accounts': '使用个人帐户开始',
    // 受管用户型企业
    'Recommended for internal work': '推荐用于内部工作',
    'Enterprise with managed users': '使用受管用户的企业',
    'For private and internal work only, with member accounts provisioned from your identity provider.': '仅适用于私有和内部工作，成员帐户由你的身份提供商配置。',
    'Choose which geographical location to store your data': '选择存储你的数据的地理位置',
    'Get started with managed users': '使用受管用户开始',

    /* -------- 企业版 按量计费(metered_ghe) / 试用与账单流程 -------- */
    'Set up GitHub Enterprise Cloud trial': '设置 GitHub Enterprise Cloud 试用版',
    'Try GitHub Enterprise for free': '免费试用 GitHub 企业版',
    'Your free trial': '你的免费试用',
    'Free trial': '免费试用',
    'Start free trial': '开始免费试用',
    'Trial ends': '试用结束',
    'days left in trial': '试用剩余天数',
    'Enterprise name': '企业名称',
    'Enterprise slug': '企业标识符',
    'Where will your enterprise live?': '你的企业将位于何处？',
    'Create enterprise': '创建企业',
    'Verify your email address': '验证你的电子邮件地址',
    'Add billing information': '添加账单信息',
    'Billing email': '计费电子邮件',
    'Billing address': '账单地址',
    'Payment method': '付款方式',
    'Card number': '卡号',
    'Name on card': '持卡人姓名',
    'Company or organization name': '公司或组织名称',
    'VAT ID': '增值税号',
    // 按量计费（官方文档术语）
    'Usage-based billing': '基于使用情况的计费',
    'Usage-based licenses': '基于使用情况的许可证',
    'Usage-based': '基于使用量',
    'Pay-as-you-go': '按量付费',
    'pay-as-you-go': '按量付费',
    'Set a usage limit': '设置使用量限制',
    'Monthly usage': '每月用量',
    'Current usage': '当前用量',
    'Billing': '计费',
    'Billing cycles': '计费周期',
    'Budgets and alerts': '预算和警报',
    'Cost centers': '成本中心',
    'Enterprise billing': '企业计费',

    /* ================= 设置页面（/settings/*） ================= */
    'Profile': '个人资料',
    'Account': '账户',
    'Billing and plans': '账单与方案',
    'Emails': '邮箱',
    'Password and authentication': '密码与身份验证',
    'Session': '会话',
    'SSH and GPG keys': 'SSH 与 GPG 密钥',
    'Models': '模型',
    'Pages': 'GitHub 页面',
    'Saved replies': '快捷回复',
    'Security log': '安全日志',
    'Sponsorship log': '赞助日志',
    'Developer settings': '开发者设置',
    'OAuth Apps': 'OAuth 应用',
    'GitHub Apps': 'GitHub 应用',
    'Installed GitHub Apps': '已安装的 GitHub 应用',
    'New personal access token': '新建个人访问令牌',
    'Generate new token': '生成新令牌',
    'Token name': '令牌名称',
    'Expiration': '有效期',
    'Select scopes': '选择权限范围',
    'repo': '仓库',
    'workflow': '工作流',
    'admin:org': '管理：组织',
    'admin:public_key': '管理：公钥',
    'admin:repo_hook': '管理：仓库钩子',
    'delete_repo': '删除仓库',
    'read:user': '读取：用户',
    'user:email': '用户：邮箱',
    'gist': '代码片段',
    'Generate token': '生成令牌',
    'Copy token': '复制令牌',
    "Make sure to copy your new personal access token now. You won't be able to see it again!": '请务必立即复制您的新个人访问令牌。之后您将无法再次查看它！',
    'Delete personal access token': '删除个人访问令牌',
    'Are you sure you want to delete this token?': '您确定要删除此令牌吗？',
    'Confirm deletion': '确认删除',
    'I understand, delete this token': '我明白，删除此令牌',

    /* ================= 仓库页面（/repos/*） ================= */
    'Starred': '已星标',
    'Pin': '固定',
    'Unpin': '取消固定',
    'Edit pins': '编辑固定项',
    'Customize your pins': '自定义您的固定项',
    'Save pins': '保存固定项',
    'Releases': '发行版',
    'Community': '社区',
    'Traffic': '流量',
    'Environments': '环境',
    'Deployments': '部署',
    'Deploy keys': '部署密钥',
    'Webhooks': 'Web 钩子',
    'Secrets and variables': '机密与变量',
    'Actions secrets': '操作机密',
    'Dependabot secrets': 'Dependabot 机密',
    'Environment secrets': '环境机密',
    'Repository secrets': '仓库机密',
    'Organization secrets': '组织机密',
    'New repository secret': '新建仓库机密',
    'New organization secret': '新建组织机密',
    'Add secret': '添加机密',
    'Update secret': '更新机密',
    'Secret': '机密值',
    'Value': '值',
    'Update': '更新',
    'No results matched your search.': '没有匹配您搜索的结果。',
    'Clear search': '清除搜索',

    /* ================= 议题/拉取请求页面 ================= */
    'Create new issue': '创建新议题',
    'Compare changes': '比较更改',
    'base': '基准分支',
    'compare': '对比分支',
    'base repository': '基准仓库',
    'head repository': '头仓库',
    'Able to merge': '可以合并',
    'These branches can be automatically merged.': '这些分支可以自动合并。',
    "Can't automatically merge": '无法自动合并',
    'Resolve conflicts': '解决冲突',
    'Create merge commit': '创建合并提交',
    'Squash and merge': '压缩并合并',
    'Rebase and merge': '变基并合并',
    'Confirm squash and merge': '确认压缩并合并',
    'Confirm rebase and merge': '确认变基并合并',
    'Close with comment': '评论并关闭',
    'Reopen issue': '重新打开议题',
    'Reopen pull request': '重新打开拉取请求',
    'Write': '编写',
    'Add your comment here...': '在此添加您的评论…',
    'Attach files by dragging & dropping, selecting or pasting them.': '通过拖拽、选择或粘贴来附加文件。',
    'Markdown is supported': '支持 Markdown',
    'Paste, drop, or click to add files': '粘贴、拖放或点击以添加文件',
    'No one assigned': '未分配',
    'Assign yourself': '分配给自己',
    'None yet': '暂无',
    'No milestone': '无里程碑',
    'Linked pull requests': '关联的拉取请求',
    'Successfully merging a pull request may close this issue.': '成功合并拉取请求可能会关闭此议题。',
    "Don't want to close this issue?": '不想关闭此议题？',
    'Linked issues': '关联的议题',
    'Reviewers': '审阅者',
    'Request review': '请求审阅',
    'Submit review': '提交审阅',
    'Files changed': '文件更改',
    'Review changes': '审阅更改',
    'Pull request successfully merged and closed': '拉取请求已成功合并并关闭',

    /* ================= 仓库设置 · 代码扫描 · AI Scan（新增工具） ================= */
    'AI Scan': 'AI 扫描',
    'AI Scan for pull requests': '用于拉取请求的 AI 扫描',
    'AI Scan for pull requests (Beta)': '用于拉取请求的 AI 扫描（测试版）',
    'AI-powered security detections': 'AI 驱动的安全检测',
    'AI-powered security detections in pull requests': '拉取请求中的 AI 驱动安全检测',
    'Generate CodeQL findings for non-CodeQL languages using AI.': '使用 AI 为非 CodeQL 语言生成 CodeQL 结果。',
    'Generate CodeQL findings for non-CodeQL languages using AI': '使用 AI 为非 CodeQL 语言生成 CodeQL 结果',
    'Generate CodeQL findings for non-CodeQL languages using': '使用 AI 为非 CodeQL 语言生成 CodeQL 结果，通过',
    'Find security vulnerabilities in pull requests with AI.': '使用 AI 查找拉取请求中的安全漏洞。',
    'Find security vulnerabilities in pull requests with AI': '使用 AI 查找拉取请求中的安全漏洞',
    'Learn more about AI Scan': '详细了解 AI 扫描',
    'Learn more about AI-powered security detections': '详细了解 AI 驱动的安全检测',
    'Enable AI Scan': '启用 AI 扫描',
    'Disable AI Scan': '禁用 AI 扫描',
    'Beta': '测试版',
    '(Beta)': '（测试版）',
    '（Beta）': '（测试版）',
    'AI Scan (Beta)': 'AI 扫描（测试版）',
    'Public preview': '公开预览',
    'Learn more about': '详细了解',
    'about AI Scan': '关于 AI 扫描',

    /* -------- 发行版说明常见标题（避免机翻出"加入物/固定"之类） -------- */
    'Added': '新增',
    'Fixed': '修复',
    'Changed': '变更',
    'Removed': '移除',
    'Deprecated': '已弃用',
    'Security': '安全',
    'Notes': '说明',
    'Changelog': '更新日志',
    "What's Changed": '变更内容',
    "What's New": '更新内容',
    'New Features': '新特性',
    'New features': '新特性',
    'Bug Fixes': '错误修复',
    'Bug fixes': '错误修复',
    'Improvements': '改进',
    'Breaking changes': '破坏性变更',
    'Breaking Changes': '破坏性变更',
    'Performance': '性能',
    'Documentation': '文档',
  },

  /* =========================== 补充正则规则 =========================== */
  regexp: [
    /* -------- 更新日志 / 公告常见句式 -------- */
    [/(GitHub Copilot weekly releases)/g, 'GitHub Copilot 每周发布'],
    [/(is generally available in GitHub Copilot)/g, '已在 GitHub Copilot 中全面上线'],
    [/(New API endpoint provides)/g, '新 API 端点提供'],
    [/(privacy-safe star history data)/g, '隐私安全的星标历史数据'],
    [/(Multiple trusted publishing configurations for npm)/g, 'npm 的多种可信发布配置'],
    [/(trusted publishing configurations for npm)/g, 'npm 的可信发布配置'],
    [/(generally available in GitHub)/g, '已在 GitHub 中全面上线'],
    [/(\d+)\s+recently viewed/g, '$1 个最近浏览'],

    /* -------- 仓库统计 -------- */
    [/(\d+)\s+Commits?\b/g, '$1 次提交'],
    [/(\d+)\s+Branches?\b/g, '$1 个分支'],
    [/(\d+)\s+Tags?\b/g, '$1 个标签'],
    [/(\d+)\s+Contributors?\b/g, '$1 位贡献者'],
    [/(\d+)\s+Releases?\b/g, '$1 个发行版'],
    [/(\d+)\s+Packages?\b/g, '$1 个软件包'],
    [/(\d+)\s+Environments?\b/g, '$1 个环境'],
    [/(\d+)\s+Deployments?\b/g, '$1 次部署'],
    [/(\d+)\s+Stars?\b/g, '$1 个星标'],
    [/(\d+)\s+Forks?\b/g, '$1 次复刻'],
    [/(\d+)\s+Watchers?\b/g, '$1 人关注'],

    /* -------- 议题/PR 统计 -------- */
    [/(\d+)\s+Open\b/g, '$1 个打开'],
    [/(\d+)\s+Closed\b/g, '$1 个已关闭'],
    [/(\d+)\s+comments?\b/g, '$1 条评论'],
    [/(\d+)\s+commits?\b/g, '$1 次提交'],
    [/(\d+)\s+files?\s+changed/g, '$1 个文件已更改'],
    [/(\d+)\s+additions?\b/g, '$1 处新增'],
    [/(\d+)\s+deletions?\b/g, '$1 处删除'],

    /* -------- 设置页面 -------- */
    [/(\d+)\s+secrets?\b/g, '$1 个机密'],
    [/(\d+)\s+variables?\b/g, '$1 个变量'],
    [/(\d+)\s+tokens?\b/g, '$1 个令牌'],
    [/(\d+)\s+keys?\b/g, '$1 个密钥'],
    [/(\d+)\s+apps?\b/g, '$1 个应用'],

    /* -------- 通知 -------- */
    [/(\d+)\s+unread/g, '$1 条未读'],
    [/(\d+)\s+notifications?\b/g, '$1 条通知'],

    /* -------- Copilot 优化目标（处理拆分文本节点或其它取值） -------- */
    [/Optimized for:\s*/g, '优化目标：'],

    /* -------- 代码扫描 · AI Scan（Beta 标记 / 拆分节点兜底） -------- */
    [/AI Scan for pull requests\s*[\(（]\s*Beta\s*[\)）]/gi, '用于拉取请求的 AI 扫描（测试版）'],
    [/Generate CodeQL findings for non-CodeQL languages using AI/gi, '使用 AI 为非 CodeQL 语言生成 CodeQL 结果'],
  ],

  /* =========================== 拆分文本补丁 =========================== */
  textPatches: [
    {
      pattern: /^\s*Ask anything or type\s*@\s*to add context\s*$/i,
      replacement: '请输入问题，或输入 @ 添加上下文',
    },
    {
      pattern: /^\s*Find a repository[.…]+\s*$/i,
      replacement: '查找仓库…',
    },
    {
      pattern: /^\s*Type\s*\/\s*to search\s*$/i,
      replacement: '按 / 搜索',
    },
    {
      pattern: /^\s*Make sure to copy your new personal access token now[.!]?\s*You won't be able to see it again[.!]?\s*$/i,
      replacement: '请务必立即复制您的新个人访问令牌。之后您将无法再次查看它！',
    },
    // 代码扫描 · AI Scan（Beta 标记常与标题拆成两个节点）
    {
      pattern: /^\s*AI Scan for pull requests\s*[\(（]\s*Beta\s*[\)）]\s*$/i,
      replacement: '用于拉取请求的 AI 扫描（测试版）',
    },
    {
      pattern: /^\s*AI Scan for pull requests\s*$/i,
      replacement: '用于拉取请求的 AI 扫描',
    },
    {
      pattern: /^\s*Generate CodeQL findings for non-CodeQL languages using AI\.?\s*$/i,
      replacement: '使用 AI 为非 CodeQL 语言生成 CodeQL 结果。',
    },
  ],

  /* 统一占位符补丁 */
  placeholderPatches: [
    { pattern: /^\s*Find a repository[.…]+\s*$/i, replacement: '查找仓库…' },
    { pattern: /^\s*Type\s*\/\s*to search\s*$/i, replacement: '按 / 搜索' },
    { pattern: /Ask anything or type\s*@\s*to add context/i, replacement: '请输入问题，或输入 @ 添加上下文' },
  ],

  /* 直接文本补丁 */
  directTextPatches: [
    { text: 'Copilot cloud agent handles routine tasks so you can focus on core work', replacement: 'Copilot 云端智能体处理日常任务，让您专注于核心工作' },
    { text: 'Save time by offloading testing, dependency upgrades, migrations and maintenance to agents. Create pull requests from Copilot Chat, CLI, IDEs or assign an issue to Copilot to get started.', replacement: '将测试、依赖升级、迁移和维护工作交给智能体，节省时间。从 Copilot Chat、CLI、IDE 创建拉取请求，或分配一个议题给 Copilot 即可开始。' },
    { text: 'View Copilot cloud agent capabilities', replacement: '查看 Copilot 云端智能体功能' },
    { text: 'Copilot cloud agent capabilities', replacement: 'Copilot 云端智能体功能' },
    { text: 'Access to Copilot cloud agent has been disabled by your administrator.', replacement: 'Copilot 云端智能体访问已被您的管理员禁用。' },
  ],

  /* =========================== 页面标题补充规则 =========================== */
  titleRegexp: [
    [/^New conversation\b/, '新对话'],
    [/^New chat\b/, '新对话'],
    [/^Chat\b/, '对话'],
    [/^Choose an Enterprise plan/, '选择企业计划'],
    [/^Set up GitHub Enterprise Cloud/, '设置 GitHub 企业版云'],
    [/^Create an enterprise/, '创建企业'],
    [/^Billing settings/, '计费设置'],
  ],

  /* =========================== 时间格式 =========================== */
  relativeTimePatterns: [
    [/(\d+)\s+seconds?\s+ago/g, '$1 秒前'],
    [/(\d+)\s+minutes?\s+ago/g, '$1 分钟前'],
    [/(\d+)\s+hours?\s+ago/g, '$1 小时前'],
    [/(\d+)\s+days?\s+ago/g, '$1 天前'],
    [/(\d+)\s+weeks?\s+ago/g, '$1 周前'],
    [/(\d+)\s+months?\s+ago/g, '$1 个月前'],
    [/(\d+)\s+years?\s+ago/g, '$1 年前'],
    [/(\d+)\s+seconds?\s+from\s+now/g, '$1 秒后'],
    [/(\d+)\s+minutes?\s+from\s+now/g, '$1 分钟后'],
    [/(\d+)\s+hours?\s+from\s+now/g, '$1 小时后'],
    [/(\d+)\s+days?\s+from\s+now/g, '$1 天后'],
    [/\bjust\s+now\b/g, '刚刚'],
    [/\byesterday\b/g, '昨天'],
    [/\btoday\b/g, '今天'],
    [/\btomorrow\b/g, '明天'],
    [/\blast\s+week\b/g, '上周'],
    [/\bnext\s+week\b/g, '下周'],
    [/\blast\s+month\b/g, '上个月'],
    [/\bnext\s+month\b/g, '下个月'],
    [/\blast\s+year\b/g, '去年'],
    [/\bnext\s+year\b/g, '明年'],
    [/\bthis\s+week\b/g, '本周'],
    [/\bthis\s+month\b/g, '本月'],
    [/\bthis\s+year\b/g, '今年'],
  ],
};
